"""Convenience re-exports for API DTOs (``requests``) and domain models (``test_case``)."""

from backend.models.browser_session import (
    AddStepBody,
    BrowserSession,
    CompleteSessionBody,
    SessionListResponse,
    SessionResponse,
    SessionStep,
    StartSessionBody,
)
from backend.models.requests import (
    CreateFeatureBody,
    CreateProjectBody,
    GenerateIterateBody,
    GenerateJsonBody,
    GenerateResponse,
    LoginBody,
    ProjectDetailResponse,
    ProjectSummaryResponse,
    RegisterBody,
    TokenResponse,
    UpdateContextBody,
    UpdateFeatureBody,
    UpdateProjectBody,
)
from backend.models.test_case import (
    Feature,
    Generation,
    GenerationInput,
    InputRecord,
    Project,
    TestCase,
    User,
)

__all__ = [
    "User",
    "Project",
    "Feature",
    "TestCase",
    "InputRecord",
    "Generation",
    "GenerationInput",
    "BrowserSession",
    "SessionStep",
    "StartSessionBody",
    "AddStepBody",
    "CompleteSessionBody",
    "SessionResponse",
    "SessionListResponse",
    "CreateProjectBody",
    "UpdateProjectBody",
    "UpdateContextBody",
    "CreateFeatureBody",
    "UpdateFeatureBody",
    "ProjectSummaryResponse",
    "ProjectDetailResponse",
    "GenerateJsonBody",
    "GenerateIterateBody",
    "GenerateResponse",
    "RegisterBody",
    "LoginBody",
    "TokenResponse",
]
