"""Browser session parser plugin.

Reads a completed browser session (recorded via MCP or agent OR generated by
the AI explorer) and builds a rich ParsedInput. For AI-explored sessions
the session's ``metadata.evidence_ledger`` is embedded directly into
``raw_context`` with citation rules — the LLM is told to cite ledger IDs
in every test case, and a downstream Critic drops uncited cases.

Two phases of input:
1. Manual recording: user records a session via POST /api/browser-session/start +
   step additions, or via POST /api/browser-session/{id}/explore for AI mode.
2. User triggers generate with input_type="browser_session" and data.session_id.
   This parser loads the session and builds ParsedInput.
"""

import json
from typing import Any

from starlette.datastructures import UploadFile

from backend.db import get_db
from backend.services import browser_session as bs_service
from backend.services.parsers.base import BaseParser, InputFieldDef, ParsedInput, ParserMeta
from backend.services.parsers.registry import ParserRegistry


def _build_raw_context_recorded(session: Any) -> str:
    """Narrative for a manually-recorded session."""
    parts: list[str] = []
    parts.append("Browser Session Recording")
    parts.append(f"URL: {session.url}")
    if session.feature_name:
        parts.append(f"Feature: {session.feature_name}")
    parts.append(f"Browser: {session.browser_type}")
    parts.append(f"Total steps: {len(session.steps)}")
    parts.append("")

    for step in session.steps:
        parts.append(f"--- Step {step.index + 1}: {step.instruction} ---")
        if step.action_type:
            parts.append(f"  Action: {step.action_type}")
        if step.target:
            parts.append(f"  Target: {step.target}")
        if step.value:
            parts.append(f"  Value: {step.value}")
        if step.status == "failed" and step.error:
            parts.append(f"  ERROR: {step.error}")
        if step.vision_description:
            parts.append(f"  Page state after action:\n    {step.vision_description}")
        if step.snapshot_yaml:
            snapshot_preview = step.snapshot_yaml[:500]
            parts.append(f"  Accessibility snapshot (excerpt):\n    {snapshot_preview}")
        parts.append("")

    return "\n".join(parts)


_LEDGER_CITATION_RULES = """
CITATION RULES (THIS IS AI-EXPLORED — STRICT):
- The EVIDENCE LEDGER below is the only source of truth. Do NOT invent
  element names, button labels, error messages, URLs, or behaviors that
  don't appear in it.
- Every test case title MUST start with "Verify" and reference an exact
  element name, page title, or error text from the ledger. Banned vague
  words: "correctly", "properly", "works", "functions".
- Every test case MUST inline-cite ledger IDs in its step text using
  square brackets: e.g., "Click 'Sign Up' button [a3]" or
  "Email error 'Invalid format' appears [e1]". Cases with NO inline
  citations will be rejected by the Critic and dropped.
- Use page IDs (pN), action IDs (aN), error IDs (eN), form IDs (fN),
  and screenshot IDs (sN) as they appear in the ledger.
- For each form in `forms[]`, write at least one happy-path case (citing
  the happy-path submit action) and one negative case per observed error
  in `errors_observed[]` (citing the error.id and the action that triggered it).
- Steps must reference exact element names from the ledger, in quotes.
- Cover happy paths AND negative scenarios grounded in observed errors.
"""


def _build_raw_context_ai_explore(session: Any, ledger_dict: dict, goal: str) -> str:
    """Narrative + Evidence Ledger for an AI-explored session.

    Embeds the citation rules directly so the standard generation prompt
    template doesn't need to know about ledger mode.
    """
    parts: list[str] = []
    parts.append("Browser Session — AI Exploration")
    parts.append(f"Starting URL: {session.url}")
    parts.append(f"Goal: {goal}")
    if session.feature_name:
        parts.append(f"Feature: {session.feature_name}")
    parts.append(f"Stop reason: {ledger_dict.get('stop_reason', 'unknown')}")

    pages = ledger_dict.get("pages") or []
    actions = ledger_dict.get("actions") or []
    errors = ledger_dict.get("errors_observed") or []
    forms = ledger_dict.get("forms") or []
    parts.append(
        f"Counts: {len(pages)} pages, {len(actions)} actions, "
        f"{len(forms)} forms, {len(errors)} errors_observed"
    )
    parts.append("")
    parts.append(_LEDGER_CITATION_RULES.strip())
    parts.append("")
    # The full ledger as JSON. Screenshots' file_paths are stripped here
    # to keep the prompt small and avoid leaking server paths.
    led_for_prompt = dict(ledger_dict)
    led_for_prompt["screenshots"] = [
        {k: v for k, v in s.items() if k != "file_path"}
        for s in (ledger_dict.get("screenshots") or [])
    ]
    parts.append("=== EVIDENCE LEDGER (JSON) ===")
    parts.append(json.dumps(led_for_prompt, ensure_ascii=False, indent=2))
    parts.append("=== END EVIDENCE LEDGER ===")
    return "\n".join(parts)


class BrowserSessionParser(BaseParser):
    meta = ParserMeta(
        name="browser_session",
        display_name="Browser Session",
        description=(
            "Record a browser session by navigating a URL and performing actions. "
            "The agent captures each step, then generates test cases from the recorded flow. "
            'Tip: say "Record my browser session on [URL]" in the chat to have the agent '
            "open a live browser where you interact and actions are captured automatically."
        ),
        input_fields=[
            InputFieldDef(
                name="session_id",
                type="text",
                label="Session ID",
                placeholder="Populated after recording",
                required=True,
            ),
        ],
        accepts_file=False,
    )

    async def parse(self, data: dict[str, Any], file: UploadFile | None) -> ParsedInput:
        session_id = str(data.get("session_id") or "").strip()
        if not session_id:
            raise ValueError("session_id is required — record a browser session first")

        async with get_db() as db:
            session = await bs_service.get_session(db, session_id)

        if not session:
            raise ValueError(f"Browser session not found: {session_id}")

        if session.status == "recording":
            raise ValueError(
                "Session is still recording. Complete the session before generating test cases."
            )

        # AI-explored sessions have an evidence_ledger in metadata. Manually
        # recorded sessions don't — fall through to the legacy narrative.
        meta = session.metadata or {}
        ledger_dict = meta.get("evidence_ledger") or None
        is_ai_explore = meta.get("mode") == "ai_explore" and isinstance(ledger_dict, dict)

        if is_ai_explore:
            goal = str(meta.get("goal") or "")
            raw_context = _build_raw_context_ai_explore(session, ledger_dict, goal)
            # Pull element names + page titles out of the ledger for the
            # structured fields used by the prompt template.
            screens = [
                f"{p.get('title','')} ({p.get('url','')})"
                for p in (ledger_dict.get("pages") or [])
            ]
            seen_elements: dict[str, None] = {}
            for a in ledger_dict.get("actions") or []:
                t = a.get("target") or {}
                n = (t.get("name") or "").strip()
                if n and n not in seen_elements:
                    seen_elements[n] = None
            ui_elements = list(seen_elements.keys())
            user_actions = [
                f"{a.get('type')} on '{(a.get('target') or {}).get('name','')}' → {a.get('outcome')}"
                for a in (ledger_dict.get("actions") or [])
            ]
        else:
            raw_context = _build_raw_context_recorded(session)
            user_actions = [
                f"Step {s.index + 1}: {s.instruction}"
                + (f" → {s.action_type} on '{s.target}'" if s.target else "")
                for s in session.steps
                if s.instruction
            ]
            screens = [
                s.vision_description
                for s in session.steps
                if s.vision_description
            ]
            ui_elements = []
            for s in session.steps:
                if s.target and s.target not in ui_elements:
                    ui_elements.append(s.target)

        feature_name = session.feature_name or "browser_session"

        parsed_meta: dict[str, Any] = {
            "session_id": session.id,
            "url": session.url,
            "browser_type": session.browser_type,
            "step_count": len(session.steps),
            "feature_name": feature_name,
            "mode": "ai_explore" if is_ai_explore else "manual_recording",
        }
        if is_ai_explore:
            # Stash the full ledger so generate.py can run the Critic.
            parsed_meta["evidence_ledger"] = ledger_dict
            parsed_meta["goal"] = str(meta.get("goal") or "")

        return ParsedInput(
            source_type="browser_session",
            feature_name=feature_name,
            screens=screens,
            ui_elements=ui_elements,
            user_actions=user_actions,
            business_rules=[],
            raw_context=raw_context,
            metadata=parsed_meta,
        )


ParserRegistry.register(BrowserSessionParser())
